# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박완우 Park Wanwoo
title: Beginner
email: rainover0824@naver.com
website: github.com/AlwaysAwake-ww

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  AlwaysAwake-ww


# Additional icon links
additional_links:
- title: Notion Page
  icon: fas fa-globe
  url: https://rainover.notion.site/c0254d9ab28a433898675c61c57dc60b

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
          안녕하세요.
          
          백엔드 개발자를 꿈꾸는 박완우입니다.
          
          C++, Java 등 객체지향 언어에 대한 이해도가 있습니다.
          
          RDBMS, SQL에 대한 이해도가 있습니다.
          
          게임 개발, 임베디드, Spring Boot 웹 개발 프로젝트 등 다양한 프로젝트 경험이 있습니다.
          
          AWS RDS, EC2 클라우드 환경에서 배포 경험이 있습니다.
          

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seokyeong University
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Computer Engineering
        # caption: 2012.03 - 2019.02
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          컴퓨터공학을 전공했습니다.

          C, C++, Java 등 프로그래밍 언어와 컴퓨터 구조, 자료구조, 알고리즘, 임베디드, 데이터베이스, 웹 개발, 확률과 통계 등의 교육과정을 수강했습니다.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 스마트 디바이스 프로그래밍 교육과정
        caption: 2019.07 ~ 2019.08
        sub_title: 멀티캠퍼스
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
            C언어, 임베디드 프로그래밍, IoT 프로젝트



  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 팀 단위 게시판
        # link: github.com/AlwaysAwake-ww/Blog
        # link_text: Project Website
        additional_links:
          - title:  blog
            icon: fab fa-github
            url: github.com/AlwaysAwake-ww/Blog
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          팀을 구성하고, 팀 단위로 게시글을 올려 타인과 공유하고 관리할 수 있는 게시판 시스템입니다.

          팀 단위 포트폴리오 공유를 목적으로 진행했습니다.





  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
